apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra
  namespace: sinatra
  labels:
    app: sinatra
    tier: web
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinatra
  template:
    metadata:
      labels:
        app: sinatra
        tier: web
        env: prod
    spec:
      containers:
        - name: sinatra
          image: IMAGE_UID_TBC
          ports:
            - containerPort: 9292
          env:
            - name: USERNAME
              valueFrom:
                configMapKeyRef:
                  name: sinatra-config
                  key: user-name
